import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useHistory, useParams } from "react-router";
import { fundIdea } from "../../store/actions/ideaAction";
import { BabeForme, Forme } from "../../style";

const InvestForm = () => {
  const ideas = useSelector((state) => state.ideas.ideas);
  const user = useSelector((state) => state.user.user);
  const ideaSlug = useParams().ideaSlug;
  const _idea = ideas.find((idea) => idea.slug === ideaSlug);

  const [idea, setIdea] = useState({
    amount: "",
    agreement: "",
  });
  const history = useHistory();
  const dispatch = useDispatch();

  const handleChange = (event) => {
    setIdea({ ...idea, [event.target.name]: event.target.value });
  };
  const handleSubmit = (event) => {
    event.preventDefault();
    const newIdea = { ...idea, ideaId: _idea.id };
    dispatch(fundIdea(newIdea));
    history.push("/checkout");
  };

  return (
    <form onSubmit={handleSubmit}>
      <Forme>
        <img
          src="https://st3.depositphotos.com/16030310/18317/v/600/depositphotos_183172678-stock-illustration-letters-logo-initial-logo-identity.jpg"
          width="100px"
          height="100px"
          alt="logo"
        />
        <h2>THIS AGREEMENT GENERATED BY START-UP HOOK</h2>
        <h3>BETWEEN</h3>
        <address>
          {(user.firstName, user.lastName)}, as investor has Jordanian
          nationality with nationalID number 99625321458 registered , where the
          context so admits, include its successors-in-title and assigns of his
          part
        </address>
        <h3>AND</h3>
        <address>
          {_idea.ideaName}, as start-up Jordanian idea looking for investment
          through The jordanian platform called <b>Startup Hooks</b> which is
          registered in all jordnian related departments with commercial Id
          number 7458666321 , where the context so admits, include its
          successors-in-title and assigns of his part
        </address>
        <h3>WHERE</h3>
        <h6>
          (A) {(user.firstName, user.lastName)}offers services, including but
          not limited to the investment of funds in accordance with the
          principles of Islamic Finance in various asset classes including Stock
          Market Investments.
          <br />
          <br />
          (B) {_idea.ideaName} desires to invest, together with other investors,
          the deposited sums stated in the investment account opening form for
          investment in the said asset classes in accordance with the terms and
          conditions of this Agreement.
        </h6>
        <context>
          <b>2.1</b> The Investor hereby agrees to entrust to Lotus Capital (the
          Investment Manager) the amount(s) stated in the investment account
          opening form and all subsequent amounts invested thereafter by the
          Investor, to be invested together with other investors’ funds for the
          purpose of the Investments specified in this Agreement as defined in
          “Investments” above. Such amount shall be remitted to the Investment
          Manager upon the signing of this agreement. <br />
          <b>2.2</b> The Investor hereby agrees to entrust to Lotus Capital (the
          Investment Manager) the amount(s) stated in the investment account
          opening form and all subsequent amounts invested thereafter by the
          Investor, to be invested together with other investors’ funds for the
          purpose of the Investments specified in this Agreement as defined in
          “Investments” above. Such amount shall be remitted to the Investment
          Manager upon the signing of this agreement. <br />
          <b>2.3</b> The Investor hereby agrees to entrust to Lotus Capital (the
          Investment Manager) the amount(s) stated in the investment account
          opening form and all subsequent amounts invested thereafter by the
          Investor, to be invested together with other investors’ funds for the
          purpose of the Investments specified in this Agreement as defined in
          “Investments” above. Such amount shall be remitted to the Investment
          Manager upon the signing of this agreement. <br />
        </context>
        <BabeForme>
          <b> I'am {(user.firstName, user.lastName)} will invest by</b>
          <br />
          <input
            type="number"
            placeholder="Investment in USD"
            name="amount"
            onChange={handleChange}
            required
          />
          <br />
          <br />
          <br />
          please enter your full name below as signeture
          <div class="input-group">
            <input
              type="text"
              aria-label="First name"
              class="form-control"
              placeholder="First Name"
            />
            <input
              type="text"
              aria-label="Last name"
              class="form-control"
              placeholder="Last Name"
            />
          </div>
          <div class="form-check">
            <input
              class="form-check-input"
              type="checkbox"
              value=""
              id="defaultCheck1"
            />
            <label class="form-check-label" for="defaultCheck1">
              I acknowledge that I have received a copy of these agreement.{" "}
            </label>
          </div>
          <div class="form-check">
            <input
              class="form-check-input"
              type="checkbox"
              value=""
              id="defaultCheck1"
            />
            <label class="form-check-label" for="defaultCheck1">
              I understand, accept and agree to comply with all terms and
              conditions of these Rules of Behavior.
            </label>
          </div>
          <button type="submit">Agree</button>
        </BabeForme>
      </Forme>
    </form>
  );
};
export default InvestForm;
